ICAO_abbr = {
    'A/A': 'Air-to-air',
    'A/G': 'Air-to-ground',
    'AAL': 'Above aerodrome level',
    'ABM': 'Abeam',
    'ABT': 'About',
    'ABV': 'Above',
    'AC': 'Altocumulus',
    'ACC': 'Area control',
    'ACFT': 'Aircraft',
    'ACK': 'Acknowledge',
    'ACL': 'Altimeter check location',
    'ACN': 'Aircraft classification number',
    'ACPT': 'Accept/ed',
    'ACT': 'Active',
    'AD': 'Aerodrome',
    'ADA': 'Advisory area',
    'ADC': 'Aerodrome chart',
    'ADDN': 'Addition/al',
    'ADJ': 'Adjacent',
    'ADR': 'Advisory route',
    'ADS': 'Automatic dependent surveillance',
    'ADVS': 'Advisory service',
    'ADZ': 'Advise',
    'AFIL': 'Flight plan filed in the air',
    'AFM': 'Affirm',
    'AFT': 'After',
    'AGA': 'Aerodromes, air routes and ground aids',
    'AGL': 'Above ground level',
    'AGN': 'Again',
    'ALERFA': 'Alert phase',
    'ALRS': 'Alerting service',
    'ALS': 'Approach lighting system',
    'ALT': 'Altitude',
    'ALTN': 'Alternate',
    'AMA': 'Area minimum altitude',
    'AMSL': 'Above mean sea level',
    'ANC': 'Aeronautical chart',
    'ANCS': 'Aeronautical navigation chart',
    'ANS': 'Answer',
    'AOC': 'Aerodrome obstacle chart',
    'AP': 'Airport',
    'APCH': 'Approach',
    'APDC': 'Aircraft parking/docking chart',
    'APN': 'Apron',
    'APP': 'Approach control',
    'APR': 'April',
    'APRX': 'Approximate/ly',
    'APSG': 'After passing',
    'APV': 'Approve/ed/al',
    'ARC': 'Area chart',
    'ARNG': 'Arrange',
    'ARO': 'Air traffic services reporting office',
    'ARP': 'Aerodrome reference point',
    'ARR': 'Arrive/al',
    'ARST': 'Arresting',
    'AS': 'Altostratus',
    'ASC': 'Ascend to',
    'ASDA': 'Accelerate-stop distance available',
    'ASPEEDG': 'Airspeed gain',
    'ASPEEDL': 'Airspeed loss',
    'ASPH': 'Asphalt',
    'ATA': 'Actual time of arrival',
    'ATC': 'Air traffic control',
    'ATD': 'Actual time of departure',
    'ATFM': 'Air traffic flow management',
    'ATM': 'Air traffic management',
    'ATP': 'At',
    'ATS': 'Air traffic services',
    'ATTN': 'Attention',
    'ATZ': 'Aerodrome traffic zone',
    'AUG': 'August',
    'AUTH': 'Authorized/ation',
    'AUW': 'All up weight',
    'AUX': 'Auxiliary',
    'AVBL': 'Available',
    'AVG': 'Average',
    'AVGAS': 'Aviation gasoline',
    'AWTA': 'Advise at what time able',
    'AWY': 'Airway',
    'AZM': 'Azimuth',
    'BA': 'Braking action',
    'BASE': 'Cloud base',
    'BCFG': 'Fog patches',
    'BCN': 'Beacon',
    'BCST': 'Broadcast',
    'BDRY': 'Boundary',
    'BECMG': 'Becoming',
    'BFR': 'Before',
    'BKN': 'Broken',
    'BLDG': 'Building',
    'BLO': 'Below clouds',
    'BLW': 'Below',
    'BR': 'Mist',
    'BRF': 'Short',
    'BRG': 'Bearing',
    'BRKG': 'Breaking',
    'BTL': 'Between layers',
    'BTN': 'Between',
    'CAT': 'Clear air turbulence',
    'CB': 'Cumulonimbus',
    'CC': 'Cirrocumulus',
    'CD': 'Candela',
    'CDN': 'Coordination',
    'CF': 'Change frequency to',
    'CFM': 'Confirm',
    'CGL': 'Circling guidance light(s)',
    'CH': 'Channel',
    'CHG': 'Modification',
    'CI': 'Cirrus',
    'CIT': 'Near or over large towns',
    'CIV': 'Civil',
    'CK': 'Check',
    'CL': 'Centre line',
    'CLA': 'Clear type of ice formation',
    'CLBR': 'Calibration',
    'CLD': 'Cloud',
    'CLG': 'Calling',
    'CLIMB-OUT': 'Climb-out area',
    'CLR': 'Clear',
    'CLRD': 'Cleared',
    'CLSD': 'Closed',
    'CMB': 'Climb to',
    'CMPL': 'Complete',
    'CNL': 'Flight plan cancellation',
    'CNS': 'Communications, navigation and surveillance',
    'COM': 'Communications',
    'CONC': 'Concrete',
    'COND': 'Condition',
    'CONS': 'Continuous',
    'CONST': 'Construction/ed',
    'CONT': 'Continued',
    'COOR': 'Coordination',
    'COORD': 'Coordinates',
    'COP': 'Change-over point',
    'COR': 'Correction',
    'COT': 'At the coast',
    'COV': 'Covered',
    'CPDLC': 'Controller-pilot data link communications',
    'CPL': 'Current flight plan',
    'CRC': 'Cyclic redundancy check',
    'CRZ': 'Cruise',
    'CS': 'Cirrostratus',
    'CTA': 'Control area',
    'CTAM': 'Climb to and maintain',
    'CTC': 'Contact',
    'CTL': 'Control',
    'CTN': 'Caution',
    'CTR': 'Control zone',
    'CU': 'Cumulus',
    'CUF': 'Cumuliform',
    'CVR': 'Cockpit voice recorder',
    'CW': 'Continuous wave',
    'CWY': 'Clearway',
    'DA': 'Decision altitude',
    'DCKG': 'Docking',
    'DCP': 'Datum crossing point',
    'DCPC': 'Direct controller-pilot communications',
    'DCT': 'Direct',
    'DEC': 'December',
    'DEG': 'Degrees',
    'DEP': 'Departure',
    'DES': 'Descend to',
    'DEST': 'Destination',
    'DETRESFA': 'Distress phase',
    'DEV': 'Deviation or deviating',
    'DFDR': 'Digital flight data recorder',
    'DFTI': 'Distance from touchdown indicator',
    'DH': 'Decision height',
    'DIP': 'Diffuse',
    'DIST': 'Distance',
    'DIV': 'Divert',
    'DLA': 'Delay',
    'DLY': 'Daily',
    'DNG': 'Danger or dangerous',
    'DOM': 'Domestic',
    'DP': 'Dew point temperature',
    'DPT': 'Depth',
    'DR': 'Dead reckoning',
    'DRG': 'During',
    'DS': 'Duststorm',
    'DTAM': 'Descend to and maintain',
    'DTG': 'Date-time group',
    'DTHR': 'Displaced runway threshold',
    'DTRT': 'Deteriorating',
    'DTW': 'Dual tandem wheels',
    'DU': 'Dust',
    'DUC': 'Dense upper cloud',
    'DUPE': 'This is a duplicate message',
    'DUR': 'Duration',
    'DVOR': 'Doppler VOR',
    'DW': 'Dual wheels',
    'DZ': 'Drizzle',
    'EAT': 'Expected approach time',
    'EB': 'Eastbound',
    'EDA': 'Elevation differential area',
    'EET': 'Estimated elapsed time',
    'EFC': 'Expect further clearance',
    'EGNOS': 'European geostationary navigation overlay service',
    'ELBA': 'Emergency location beacon',
    'ELEV': 'Elevation',
    'ELR': 'Extra long range',
    'EM': 'Emission',
    'EMBD': 'Embedded in a layer',
    'EMERG': 'Emergency',
    'END': 'Stop-end',
    'ENE': 'East-north-east',
    'ENG': 'Engine',
    'ENR': 'En-route',
    'ENRC': 'En-route chart',
    'EOBT': 'Estimated off-block time',
    'EQPT': 'Equipment',
    'ER': 'Here',
    'ESE': 'East-south-east',
    'EST': 'Estimate',
    'ETA': 'Estimated time of arrival',
    'ETD': 'Estimated time of departure',
    'ETO': 'Estimated time over significant point',
    'EV': 'Every',
    'EXC': 'Except',
    'EXER': 'Exercise',
    'EXP': 'Expect',
    'EXTD': 'Extend',
    'FAC': 'Facilities',
    'FAF': 'Final approach fix',
    'FAL': 'Facilitation of international airtransport',
    'FAP': 'Final approach point',
    'FATO': 'Final approach and take-off area',
    'FAX': 'Fax',
    'FBL': 'Light',
    'FC': 'Funnel cloud',
    'FCST': 'Forecast',
    'FCT': 'Friction coefficient',
    'FDPS': 'Flight data processing system',
    'FEB': 'February',
    'FEW': 'Few',
    'FG': 'Fog',
    'FLD': 'Field',
    'FLG': 'Flashing',
    'FLR': 'Flares',
    'FLT': 'Flight',
    'FLTCK': 'Flight check',
    'FLUC': 'Fluctuating',
    'FLW': 'Follow(s)',
    'FLY': 'Fly',
    'FM': 'From',
    'FMS': 'Flight management system',
    'FMU': 'Flow management unit',
    'FNA': 'Final approach',
    'FPAP': 'Flight path alignment point',
    'FPL': 'Filed flight plan',
    'FPM': 'Feet per minute',
    'FPR': 'Flight plan route',
    'FR': 'Fuel remaining',
    'FREQ': 'Frequency',
    'FRI': 'Friday',
    'FRNG': 'Firing',
    'FRONT': 'Front',
    'FRQ': 'Frequent',
    'FSL': 'Full stop landing',
    'FSS': 'Flight service station',
    'FST': 'First',
    'FTP': 'Fictitious threshold point',
    'FU': 'Smoke',
    'FZ': 'Freezing',
    'FZDZ': 'Freezing drizzle',
    'FZFG': 'Freezing fog',
    'FZRA': 'Freezing rain',
    'G/A': 'Ground-to-air',
    'G/A/G': 'Ground-to-air and air-to-ground',
    'GARP': 'GBAS azimuth reference point',
    'GBAS': 'Ground-based augmentation system',
    'GCAJ': 'Ground controlled approach',
    'GEN': 'General',
    'GEO': 'Geographic or true',
    'GES': 'Ground earth station',
    'GLD': 'Glider',
    'GMC': 'Ground movement chart',
    'GND': 'Ground',
    'GNDCK': 'Ground check',
    'GP': 'Glide path',
    'GR': 'Hail',
    'GRASS': 'Grass landing area',
    'GRVL': 'Gravel',
    'GS': 'Small hail and/or snow pellets',
    'GUND': 'Geoid undulation',
    'H24': 'Continuous day and night service',
    'HAPI': 'Helicopter approach path indicator',
    'HBN': 'Hazard beacon',
    'HDG': 'Heading',
    'HEL': 'Helicopter',
    'HJ': 'Sunrise to sunset',
    'HLDG': 'Holding',
    'HN': 'Sunset to sunrise',
    'HO': 'Service available to meet operational requirements',
    'HOL': 'Holiday',
    'HOSP': 'Hospital aircraft',
    'HOT': 'Height',
    'HPA': 'Hectopascal',
    'HR': 'Hours',
    'HS': 'Service available during hours of scheduled operations',
    'HURCN': 'Hurricane',
    'HVY': 'Heavy',
    'HX': 'No specific working hours',
    'HYR': 'Higher',
    'IAC': 'Instrument approach chart',
    'IAF': 'Initial approach fix',
    'IAO': 'In and out of clouds',
    'IAP': 'Instrument approach procedure',
    'IAR': 'Intersection of air routes',
    'IBN': 'Identification beacon',
    'IC': 'Ice crystals',
    'ICE': 'Icing',
    'ID': 'Identifier',
    'IDENT': 'Identification',
    'IF': 'Intermediate approach fix',
    'IFF': 'Identification friend/foe',
    'IGA': 'International general aviation',
    'IM': 'Inner marker',
    'IMPR': 'Improve or improving',
    'IMT': 'Immediate or immediately',
    'INA': 'Initial approach',
    'INBD': 'Inbound',
    'INC': 'In cloud',
    'INCERFA': 'Uncertainty phase',
    'INFO': 'Information',
    'INOP': 'Inoperative',
    'INP': 'If not possible',
    'INPR': 'In progress',
    'INSTL': 'Installation',
    'INSTR': 'Instrument',
    'INT': 'Intersection',
    'INTS': 'Intersections',
    'INTL': 'International',
    'INTRG': 'Interrogator',
    'INTRP': 'Interruption',
    'INTSF': 'Intensifying',
    'INTST': 'Intensity',
    'IR': 'Ice on runway',
    'ISA': 'International standard atmosphere',
    'ISOL': 'Isolated',
    'JAN': 'January',
    'JTST': 'Jet stream',
    'JUL': 'July',
    'JUN': 'June',
    'KMH': 'Kilometres per hour',
    'KPA': 'Kilopascal',
    'KT': 'Knots',
    'KW': 'Kilowatts',
    'LAN': 'Inland',
    'LAT': 'Latitude',
    'LDA': 'Landing distance available',
    'LDAH': 'Landing distance available, helicopter',
    'LDG': 'Landing',
    'LDI': 'Landing direction indicator',
    'LEN': 'Length',
    'LGT': 'Light or lighting',
    'LGTD': 'Lighted',
    'LIH': 'Light intensity high',
    'LIL': 'Light intensity low',
    'LIM': 'Light intensity medium',
    'LLZ': 'Localizer',
    'LM': 'Locator, middle',
    'LMT': 'Local mean time',
    'LNG': 'Long',
    'LO': 'Locator, outer',
    'LOG': 'Local/tion/ted',
    'LONG': 'Longitude',
    'LRG': 'Long range',
    'LTD': 'Limited',
    'LTP': 'Landing threshold point',
    'LV': 'Light and variable',
    'LVE': 'Leave',
    'LVL': 'Level',
    'LYR': 'Layer',
    'MAA': 'Maximum authorized altitude',
    'MAG': 'Magnetic',
    'MAINT': 'Maintenance',
    'MAP': 'Aeronautical maps and charts',
    'MAPT': 'Missed approach point',
    'MAR': 'March',
    'MAX': 'Maximum',
    'MAY': 'May',
    'MBST': 'Microburst',
    'MCA': 'Minimum crossing altitude',
    'MCW': 'Modulated continuous wave',
    'MDA': 'Minimum descent altitude',
    'MDH': 'Minimum descent height',
    'MEA': 'Minimum en-route altitude',
    'MEHT': 'Minimum eye height over threshold',
    'MET': 'Meteorological',
    'MID': 'Mid-point',
    'MIFG': 'Shallow fog',
    'MIL': 'Military',
    'MIN': 'Minutes',
    'MKR': 'Marker radio beacon',
    'MLS': 'Microwave landing system',
    'MM': 'Middle marker',
    'MNM': 'Minimum',
    'MNPS': 'Minimum navigation performance specifications',
    'MNT': 'Monitor',
    'MNTN': 'Maintain',
    'MOA': 'Military operating area',
    'MOC': 'Minimum obstacle clearance',
    'MOD': 'Moderate',
    'MON': 'Monday',
    'MOPS': 'Minimum operational performance standards',
    'MOV': 'Movement',
    'MRA': 'Minimum reception altitude',
    'MRG': 'Medium range',
    'MRP': 'ATS/MET reporting point',
    'MS': 'Minus',
    'MSA': 'Minimum sector altitude',
    'MSAW': 'Minimum safe altitude warning',
    'MSG': 'Message',
    'MSL': 'Mean sea level',
    'MSSR': 'Monopulse secondary surveillance radar',
    'MT': 'Mountain',
    'MTU': 'Metric units',
    'MTW': 'Mountain waves',
    'MX': 'Mixed type of ice formation (white and clear)',
    'NASC': 'National AIS system centre',
    'NAT': 'North Atlantic',
    'NAV': 'Navigation',
    'NB': 'Northbound',
    'NBFR': 'Not before',
    'NC': 'No change',
    'NCD': 'No cloud detected',
    'NDV': 'No directional variations available',
    'NE': 'North-east',
    'NEB': 'North-eastbound',
    'NEG': 'Negative',
    'NGT': 'Night',
    'NIL': 'None',
    'NML': 'Normal',
    'NNE': 'North-north-east',
    'NNW': 'North-north-west',
    'NOF': 'International NOTAM office',
    'NOSIG': 'No significant change',
    'NOV': 'November',
    'NOZ': 'Normal operating zone',
    'NR': 'Number',
    'NRH': 'No reply heard',
    'NS': 'Nimbostratus',
    'NSC': 'Nil significant cloud',
    'NSW': 'Nil significant weather',
    'NTL': 'National',
    'NTZ': 'No transgression zone',
    'NW': 'North-west',
    'NWB': 'North-westbound',
    'NXT': 'Next',
    'O/R': 'On request',
    'OAC': 'Oceanic area control centre',
    'OAS': 'Obstacle assessment surface',
    'OBS': 'Observe',
    'OBSC': 'Obscured',
    'OBST': 'Obstacle',
    'OCA': 'Oceanic control area',
    'OCC': 'Occulting (light)',
    'OCH': 'Obstacle clearance height',
    'OCNL': 'Occasional or occasionally',
    'OCS': 'Obstacle clearance surface',
    'OCT': 'October',
    'OFZ': 'Obstacle free zone',
    'OGN': 'Originate',
    'OHD': 'Overhead',
    'OM': 'Outer marker',
    'OPA': 'Opaque ice',
    'OPC': 'Control indicated is operational control',
    'OPMET': 'Operational meteorological',
    'OPN': 'Open',
    'OPR': 'Operational',
    'OPS': 'Operations',
    'ORD': 'Order',
    'OSV': 'Ocean station vessel',
    'OTLK': 'Outlook',
    'OTP': 'On top',
    'OTS': 'Organized track system',
    'OUBD': 'Outbound',
    'OVC': 'Overcast',
    'PA': 'Precision approach',
    'PALS': 'Precision approach lighting system',
    'PANS': 'Procedures for air navigation services',
    'PAR': 'Precision approach radar',
    'PARL': 'Parallel',
    'PATC': 'Precision approach terrain chart',
    'PAX': 'Passenger(s)',
    'PCD': 'Proceed',
    'PCL': 'Pilot-controlled lighting',
    'PCN': 'Pavement classification number',
    'PDC': 'Pre-departure clearance',
    'PDG': 'Procedure design gradient',
    'PER': 'Performance',
    'PERM': 'Permanent',
    'PIB': 'Pre-flight information bulletin',
    'PJE': 'Parachute jumping exercise',
    'PL': 'Ice pellets',
    'PLA': 'Practice low approach',
    'PLN': 'Flight plan',
    'PLVL': 'Present level',
    'PN': 'Prior notice required',
    'PNR': 'Point of no return',
    'PO': 'Dust/sand whirls',
    'POB': 'Persons on board',
    'POSS': 'Possible',
    'PPI': 'Plan position indicator',
    'PPR': 'Prior permission required',
    'PPSN': 'Present position',
    'PRFG': 'Aerodrome partially covered by fog',
    'PRI': 'Primary',
    'PRKG': 'Parking',
    'PROB': 'Probability',
    'PROC': 'Procedure',
    'PROV': 'Provisional',
    'PS': 'Plus',
    'PSG': 'Passing',
    'PSN': 'Position',
    'PSR': 'Primary surveillance radar',
    'PSYS': 'Pressure system(s)',
    'PTN': 'Procedure turn',
    'PTS': 'Polar track structure',
    'PWR': 'Power',
    'QUAD': 'Quadrant',
    'RA': 'Rain',
    'RAC': 'Rules of the air and air traffic services',
    'RAG': 'Runway arresting gear',
    'RAI': 'Runway alignment indicator',
    'RAIM': 'Receiver autonomous integrity monitoring',
    'RASC': 'Regional AIS system centre',
    'RASS': 'Remote altimeter setting source',
    'RB': 'Rescue boat',
    'RCA': 'Reach cruising altitude',
    'RCC': 'Rescue coordination centre',
    'RCF': 'Radiocommunication failure',
    'RCH': 'Reach or reaching',
    'RCL': 'Runway centre line',
    'RCLL': 'Runway centre line light(s)',
    'RCLR': 'Recleared',
    'RDH': 'Reference datum height',
    'RDL': 'Radial',
    'RDO': 'Radio',
    'RE': 'Recent',
    'REC': 'Receiver',
    'REDL': 'Runway edge light(s)',
    'REF': 'Reference to',
    'REG': 'Registration',
    'RENL': 'Runway end light(s)',
    'REP': 'Report',
    'REQ': 'Request',
    'RERTE': 'Re-route',
    'RESA': 'Runway end safety area',
    'RG': 'Range (lights)',
    'RHC': 'Right-hand circuit',
    'RIF': 'Reclearance in flight',
    'RITE': 'Right',
    'RL': 'Report leaving',
    'RLA': 'Relay to',
    'RLCE': 'Request level change en route',
    'RLLS': 'Runway lead-in lighting system',
    'RLNA': 'Request level not available',
    'RMAC': 'Radar minimum altitude chart',
    'RMK': 'Remark',
    'RNG': 'Radio range',
    'RNP': 'Required navigation performance',
    'ROC': 'Rate of climb',
    'ROD': 'Rate of descent',
    'ROFOR': 'Route forecast',
    'RON': 'Receiving only',
    'RPI': 'Radar position indicator',
    'RPL': 'Repetitive flight plan',
    'RPLC': 'Replaced',
    'RPS': 'Radar position symbol',
    'RQMNTS': 'Requirements',
    'RQP': 'Request flight plan',
    'RQS': 'Request supplementary flight plan',
    'RR': 'Report reaching',
    'RSC': 'Rescue sub-centre',
    'RSCD': 'Runway surface condition',
    'RSP': 'Responder beacon',
    'RSR': 'En-route surveillance radar',
    'RTE': 'Route',
    'RTF': 'Radiotelephone',
    'RTG': 'Radiotelegraph',
    'RTHL': 'Runway threshold light(s)',
    'RTN': 'Return',
    'RTODAH': 'Rejected take-off distance available, helicopter',
    'RTS': 'Return to service',
    'RTT': 'Radioteletypewriter',
    'RTZL': 'Runway touchdown zone light(s)',
    'RUT': 'Standard regional route transmitting frequencies',
    'RV': 'Rescue vessel',
    'RVR': 'Runway visual range',
    'RVSM': 'Reduced vertical separation minimum',
    'RWY': 'Runway',
    'SA': 'Sand',
    'SALS': 'Simple approach lighting system',
    'SAN': 'Sanitary',
    'SAP': 'As soon as possible',
    'SAR': 'Search and rescue',
    'SARPS': 'Standards and Recommended Practices',
    'SAT': 'Saturday',
    'SATCOM': 'Satellite communication',
    'SB': 'Southbound',
    'SBAS': 'Satellite-based augmentation system',
    'SC': 'Stratocumulus',
    'SCT': 'Scattered',
    'SDBY': 'Stand by',
    'SE': 'South-east',
    'SEA': 'Sea',
    'SEB': 'South-eastbound',
    'SEC': 'Seconds',
    'SECN': 'Section',
    'SECT': 'Sector',
    'SEP': 'September',
    'SER': 'Service',
    'SEV': 'Severe',
    'SFC': 'Surface',
    'SG': 'Snow grains',
    'SGL': 'Signal',
    'SID': 'Standard instrument departure',
    'SIF': 'Selective identification feature',
    'SIG': 'Significant',
    'SIMUL': 'Simultaneous',
    'SKC': 'Sky clear',
    'SKED': 'Schedule or scheduled',
    'SLP': 'Speed limiting point',
    'SLW': 'Slow',
    'SMC': 'Surface movement control',
    'SMR': 'Surface movement radar',
    'SN': 'Snow',
    'SNOCLO': 'Aerodrome closed due to snow',
    'SPL': 'Supplementary flight plan',
    'SPOC': 'SAR point of contact',
    'SPOT': 'Spot wind',
    'SQ': 'Squall',
    'SQL': 'Squall line',
    'SR': 'Sunrise',
    'SRA': 'Surveillance radar approach',
    'SRE': 'Surveillance radar element of precision approach radar system',
    'SRG': 'Short range',
    'SRR': 'Search and rescue region',
    'SRY': 'Secondary',
    'SS': 'Sunset',
    'SSE': 'South-south-east',
    'SSR': 'Secondary surveillance radar',
    'SST': 'Supersonic transport',
    'SSW': 'South-south-west',
    'ST': 'Stratus',
    'STA': 'Straight-in approach',
    'STAR': 'Standard instrument arrival',
    'STD': 'Standard',
    'STF': 'Stratiform',
    'STN': 'Station',
    'STNR': 'Stationary',
    'STOL': 'Short take-off and landing',
    'STS': 'Status',
    'STWL': 'Stopway light(s)',
    'SUBJ': 'Subject to',
    'SUN': 'Sunday',
    'SUP': 'AIP Supplement)',
    'SUPPS': 'Regional supplementary procedures Service message',
    'SVCBL': 'Serviceable',
    'SW': 'South-west',
    'SWB': 'South-westbound',
    'SWY': 'Stopway',
    'TA': 'Transition altitude',
    'TAA': 'Terminal arrival altitude',
    'TAF': 'Aerodrome forecast',
    'TAIL': 'Tail wind',
    'TAR': 'Terminal area surveillance radar',
    'TAX': 'Taxi',
    'TC': 'Tropical cyclone',
    'TCAC': 'Tropical cyclone advisory centre',
    'TCU': 'Towering cumulus',
    'TDO': 'Tornado',
    'TDZ': 'Touchdown zone',
    'TECR': 'Technical reason',
    'TEL': 'Telephone',
    'TEMPO': 'Temporarily',
    'TFC': 'Traffic',
    'TGL': 'Touch-and-go',
    'TGS': 'Taxiing guidance system',
    'THR': 'Threshold',
    'THRU': 'Through',
    'THU': 'Thursday',
    'TIBA': 'Traffic information broadcast by aircraft',
    'TIL': 'Until',
    'TIP': 'Until past',
    'TKOF': 'Take-off',
    'TL': 'Till',
    'TLOF': 'Touchdown and lift-off area',
    'TMA': 'Terminal control area',
    'TNA': 'Turn altitude',
    'TNH': 'Turn height',
    'TO': 'To',
    'TOC': 'Top of climb',
    'TODA': 'Take-off distance available',
    'TODAH': 'Take-off distance available, helicopter',
    'TOP': 'Cloud top',
    'TORA': 'Take-off run available',
    'TP': 'Turning point',
    'TR': 'Track',
    'TRA': 'Temporary reserved airspace',
    'TRANS': 'Transmitter',
    'TREND': 'Trend forecast',
    'TRL': 'Transition level',
    'TROP': 'Tropopause',
    'TS': 'Thunderstorm',
    'TUE': 'Tuesday',
    'TURB': 'Turbulence',
    'TVOR': 'Terminal VOR',
    'TWR': 'Tower',
    'TWY': 'Taxiway',
    'TWYL': 'Taxiway-link',
    'TXT': 'Text',
    'TYP': 'Type of aircraft',
    'TYPH': 'Typhoon',
    'U/S': 'Unserviceable',
    'UAB': 'Until advised by',
    'UAC': 'Upper area control centre',
    'UAR': 'Upper air route',
    'UFN': 'Until further notice',
    'UHDT': 'Unable higher due traffic',
    'UIC': 'Upper information centre',
    'UIR': 'Upper flight information region',
    'ULR': 'Ultra long range',
    'UNA': 'Unable',
    'UNAP': 'Unable to approve',
    'UNL': 'Unlimited',
    'UNREL': 'Unreliable',
    'UP': 'Unidentified precipitation',
    'UTA': 'Upper control area',
    'VA': 'Volcanic ash',
    'VAAC': 'Volcanic ash advisory centre',
    'VAC': 'Visual approach chart',
    'VAL': 'In valleys',
    'VAN': 'Runway control van',
    'VAR': 'Visual-aural radio range',
    'VC': 'Vicinity',
    'VCY': 'Vicinity',
    'VER': 'Vertical',
    'VIS': 'Visibility',
    'VLR': 'Very long range',
    'VPA': 'Vertical path angle',
    'VRB': 'Variable',
    'VSA': 'By visual reference to the ground',
    'VSP': 'Vertical speed',
    'VTOL': 'Vertical take-off and landing',
    'WAC': 'World Aeronautical Chart',
    'WAFC': 'World area forecast centre',
    'WB': 'Westbound',
    'WBAR': 'Wing bar lights',
    'WDI': 'Wind direction indicator',
    'WDSPR': 'Widespread',
    'WED': 'Wednesday',
    'WEF': 'Effective from',
    'WI': 'Within',
    'WID': 'Width',
    'WIE': 'Effective immediately',
    'WILCO': 'Will comply',
    'WIND': 'Wind',
    'WINTEM': 'Forecast upper wind and temperature for aviation',
    'WIP': 'Work in progress',
    'WKN': 'Weaken',
    'WNW': 'West-north-west',
    'WO': 'Without',
    'WPT': 'Way-point',
    'WRNG': 'Warning',
    'WS': 'Wind shear',
    'WSPD': 'Wind speed',
    'WSW': 'West-south-west',
    'WT': 'Weight',
    'WTSPT': 'Waterspout',
    'WWW': 'Worldwide web',
    'WX': 'Weather',
    'XBAR': 'Crossbar',
    'XNG': 'Crossing',
    'XS': 'Atmospherics',
    'YCZ': 'Yellow caution zone',
    'YR': 'Your',
}